version: '3.8'

services:
  postgres:
    build: ./postgres
    container_name: keyhole_postgres
    restart: always
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./src:/app  # Mount your Python scripts folder

volumes:
  pg_data:

